import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-secondary-container': '#99b5ee',
        'secondary-fixed': '#d7e2ff',
        'on-primary-fixed-variant': '#004883',
        'on-surface': '#e1e2e8',
        primary: '#a4c9ff',
        'surface-container-highest': '#333539',
        'on-tertiary-container': '#392600',
        'primary-fixed-dim': '#a4c9ff',
        'on-tertiary-fixed-variant': '#5d4200',
        'on-primary-container': '#002a51',
        'inverse-primary': '#2560a0',
        secondary: '#acc7ff',
        'on-secondary-fixed': '#001a40',
        background: '#111318',
        'surface-tint': '#a4c9ff',
        'secondary-container': '#294678',
        'primary-fixed': '#d4e3ff',
        'on-primary-fixed': '#001c39',
        'surface-container-high': '#282a2f',
        'surface-bright': '#37393e',
        'on-error-container': '#ffdad6',
        'surface-variant': '#333539',
        'surface-container-lowest': '#0c0e12',
        'on-primary': '#00315d',
        'surface-container': '#1d2024',
        'on-error': '#690005',
        'on-tertiary-fixed': '#271900',
        tertiary: '#f4be52',
        'error-container': '#93000a',
        'outline-variant': '#424750',
        'secondary-fixed-dim': '#acc7ff',
        'on-tertiary': '#412d00',
        error: '#ffb4ab',
        'on-secondary': '#0d2f60',
        'surface-dim': '#111318',
        'inverse-on-surface': '#2e3035',
        'tertiary-container': '#b8891f',
        'primary-container': '#5f93d6',
        'on-secondary-fixed-variant': '#294678',
        'tertiary-fixed': '#ffdea6',
        outline: '#8c919b',
        'inverse-surface': '#e1e2e8',
        'tertiary-fixed-dim': '#f4be52',
        'on-surface-variant': '#c2c6d2',
        'surface-container-low': '#191c20',
        'on-background': '#e1e2e8',
        surface: '#111318',
      },
      spacing: {
        unit: '4px',
        'section-padding': '80px',
        'container-max': '1200px',
        gutter: '24px',
      },
      maxWidth: {
        'container-max': '1200px',
      },
      fontFamily: {
        'label-caps': ['var(--font-space-mono)', 'monospace'],
        'mono-data': ['var(--font-space-mono)', 'monospace'],
        h1: ['var(--font-space-mono)', 'monospace'],
        h2: ['var(--font-space-mono)', 'monospace'],
        h3: ['var(--font-space-mono)', 'monospace'],
        'body-md': ['var(--font-inter)', 'sans-serif'],
        'body-lg': ['var(--font-inter)', 'sans-serif'],
      },
      fontSize: {
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '700' }],
        'mono-data': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        h1: ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        h2: ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '700' }],
        h3: ['18px', { lineHeight: '1.4', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}

export default config
